import { Inter } from "next/font/google"

import Header from "@/common/components/Header"
import Footer from "@/common/components/Footer"

import ReduxProvider from "@data/ReduxProvider"

import { getStoreConfig } from "@common/services"
import { getCurrentLocale } from "@locales/server"

import "@common/styles/global.scss"
import "@common/styles/app.scss"
import "slick-carousel/slick/slick.scss"
import "slick-carousel/slick/slick-theme.scss"
import "react-loading-skeleton/dist/skeleton.css"
import { AuthProvider } from "@data/context/AuthContext"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

/**
 * Common layout that shares acrose the site
 */
export default async function RootLayout({ children, params }) {
  const currLocale = getCurrentLocale()
  const storeConfigData = await getStoreConfig()

  // in future this data will come from cookies
  const authData = {
    token: "server_token",
    user: "dishant",
    loading: "idle",
    formData: {},
    formErrorMessage: null,
    loadingType: "social",
  }

  return (
    <html lang={currLocale} dir={currLocale === "ar-sa" ? "rtl" : "ltr"}>
      <>
      <body >
        <ReduxProvider>
          <AuthProvider initialState={authData}>
            <Header />
            <div className="main">{children}</div>
            <Footer />
          </AuthProvider>
        </ReduxProvider>
      </body>
      </>
    </html>
  )
}
